# Generated by Django 6.0.5 on 2026-06-21 13:53

import account.util
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('lecturer_i', 'Lecturer I'), ('lecturer_ii', 'Lecturer II'), ('sr_lecturer', 'Senior Lecturer'), ('professor', 'Professor'), ('hod', 'Head of Department')], default='lecturer_i', max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('level', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('matric_number', models.CharField(default=account.util.generate_matric_number, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_year', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'student_account',
                'ordering': ['matric_number'],
            },
        ),
    ]
